apiVersion: apps/v1
kind: Deployment
metadata:
  name: mypizza
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mypizza
  template:
    metadata:
      labels:
        app: mypizza
    spec:
      containers:
      - name: mypizza
        image: k4mus/mypizza:6
        ports:
        - containerPort: 8000
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "250m"
            memory: "256Mi"
