apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: mypizza
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mypizza-deployment
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
